server:
  port: 8081
spring:
  application:
    name: nutrition-services
  data:
    mongodb:
      database: Greethy
      host: localhost
      port: 27017
  cloud:
    consul:
      discovery:
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${server.port}}}
