version: '3.3'

services:
  #AXON_SERVER
  axonserver:
    image: axoniq/axonserver
    hostname: greethy-axonserver
    volumes:
      - type: bind
        source: ./axon/data
        target: /axon/data
      - type: bind
        source: ./axon/events
        target: /axon/eventdata
      - type: bind
        source: ./axon/config
        target: /axon/config
        read_only: true
    ports:
      - '8024:8024'
      - '8124:8124'
    environment:
      - AXONIQ_AXONSERVER_DEVMODE_ENABLED=true

  #DATASOURCE_MONGODB
  mongodb:
    image: mongo:latest
    container_name: greethy-mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/mongodb/data
    environment:
      MONGODB_INITDB_ROOT_USERNAME: root
      MONGODB_INITDB_ROOT_PASSWORD: 123456

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  #AUTHSERVER_KEYCLOAK
  keycloak:
    image: quay.io/keycloak/keycloak
    container_name: greethy-keycloak
    ports:
      - "8080:8080"
    command:
      - start-dev
      - --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HEALTH_ENABLED: true
    depends_on:
      - postgres
    volumes:
      - /home/keycloak/realm.json:/opt/keycloak/data/import/realm.json

volumes:
  axonserver-data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/axon/data
      o: bind
  axonserver-events:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/axon/events
      o: bind
  axonserver-config:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/axon/config
      o: bind
  mongodb_data:
  postgres:
