version: '3'

networks:
  backend:
  frontend:

services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    container_name: keycloak
    hostname: keycloak
    ports:
      - "8080:8080"
    environment:
      DB_VENDOR: MONGO
      DB_ADDR: db
      DB_DATABASE: keycloak_db
      KEYCLOAK_HOST_NAME: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start-dev
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7.0.2
    container_name: mongodb
    hostname: mongodb
    ports:
      - "27017:27017"

