spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888
application:
  password: F!(h3hZXjeGKr+9hB#+kw*pv7gtAs@Y3
  jwt:
    iss: accounts.greethy.com
    secret-key: ecf1222c-88fd-47f3-988f-bdd78bade1ad