# SERVER CONFIG
server:
  port: 8222

# GATEWAY CONFIG
spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
      discovery:
        locator:
          enabled: true

# EUREKA CLIENT CONFIG
eureka:
  server:
    host: localhost:8761
  client:
    service-url:
      defaultZone: http://${eureka.server.host}/eureka
    register-with-eureka: true
    fetch-registry: true

# ACTUATOR CONFIG
management:
  endpoints:
    gateway:
      enabled: true
  endpoint:
    web:
      exposure:
        include: gateway
