#SERVER CONFIG
server:
  port: 8555

#APPLICATION CONFIG
spring:
  cloud:
    profile: dev

#DATA SOURCE CONFIG
  data:
    mongodb:
      database: Greethy_User
      host: localhost
      port: 27017

#EUREKA CONFIG
eureka:
  server:
    host: localhost:8761
  client:
    service-url:
      defaultZone: http://${eureka.server.host}/eureka
    register-with-eureka: true
    fetch-registry: false