spring:
  application:
    name: personal-services
  data:
    mongodb:
      database: GreethyDB
      host: localhost
      port: 27017
      username: root
      password: password
      authentication-database: admin
server:
  port: 8085

eureka:
  server:
    host: localhost:8761
  client:
    service-url:
      defaultZone: http://${eureka.server.host}/eureka
    register-with-eureka: true
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    env:
      enabled: true