server:
  port: 8888
spring:
  application.name: config-server
  cloud:
    config:
      server:
        git:
          uri:
management:
  health:
    livenessstate.enabled: true
    readinessstate.enabled: true
  endpoint:
    health:
      probes:
        enabled: true
eureka:
  server:
    hostname: localhost:8761
  client:
    service-url:
      defaultZone: http://${eureka.server.hostname}/eureka
