server:
  port: 8181

spring:
  application:
    name: user-command
  data:
    mongodb:
      host: localhost
      port: 27017
      database: GreethyUser
  kafka:
    topic: greethy.topic.user-topic
    consumer:
      bootstrap-servers: localhost:29092
      group-id: user-reactive-kafka-consumer
      auto-offset-reset: earliest
    producer:
      bootstrap-servers: localhost:29092

springdoc:
  swagger-ui:
    use-root-path: true
  api-docs:
    version: openapi_3_1
  show-actuator: true

management:
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    env:
      enabled: true