server:
  port: 8181

spring:
  application:
    name: user-command
  data:
    mongodb:
      host: localhost
      port: 27017
      database: GreethyUser
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      topic: greethy-nutrition-sys-bodyspec-v1
      group-id: user-reactive-kafka-consumer
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer:

springdoc:
  swagger-ui:
    use-root-path: true
    security-scheme-name: Authentication Bearer
  api-docs:
    version: openapi_3_1
  show-actuator: true

management:
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    env:
      enabled: true