server:
  port: 8082
spring:
  application:
    name: user-command
  data:
    mongodb:
      host: localhost
      port: 27017
      database: GreethyUser

springdoc:
  swagger-ui:
    use-root-path: true
  api-docs:
    version: openapi_3_1
  show-actuator: true

custom:
  api:
    path:
      prefix: /api/v1

management:
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    env:
      enabled: true